<?php 
include '../Config.php';
include '../dbh.php';	
include '../postAndToken.php';


  //Acá falta la seguridad!!!!!!!! Poner despues de probar bien todo!

	$query= "SELECT     'Valor' AS Tipo, ENTIDADES.DS_RAZON_SOCIAL, ENTIDADES.CD_CUIT, 
                      ENTIDADES_UBICACIONES.DS_DIRECCION + ' ' + ENTIDADES_UBICACIONES.DS_NUMERO + ' ' + ENTIDADES_UBICACIONES.DS_PISO + ' ' + ENTIDADES_UBICACIONES.DS_DPTO
                       AS Direccion, ' (' + ENTIDADES_UBICACIONES.CD_CP + ') ' + LOCALIDADES.DS_LOCALIDAD + ' - ' + PROVINCIAS.DS_PROVINCIA + ' - ' + PAISES.DS_PAIS AS Localidad,
                       CC_RECIBOS.TP_RECIBO + '-' + CC_RECIBOS.NO_EMISOR + '-' + CC_RECIBOS.NO_RECIBO AS RECIBO, CC_RECIBOS.DT_EMISION, 
                      VALOR_TIPOS.DS_VALOR_TIPO, 
                      CASE WHEN cc_recibos_valores.CD_valor_tipo = 'CH' THEN CAJA_VALORES.DT_EMISION WHEN cc_recibos_valores.CD_valor_tipo = 'RN' THEN Retenciones.dt_emision
                       END AS Emision, 
                      CASE WHEN cc_recibos_valores.CD_valor_tipo = 'CH' THEN CAJA_VALORES.DT_VENCE WHEN cc_recibos_valores.CD_valor_tipo = 'RN' THEN Retenciones.dt_emision
                       END AS Vence, 
                      CASE WHEN cc_recibos_valores.CD_valor_tipo = 'CH' THEN CAJA_VALORES.ID_VALOR_EXTERNO WHEN cc_recibos_valores.CD_valor_tipo = 'RN' THEN retenciones.Id_cbte_externo
                       END AS Comprobante, CONCEPTOS.DS_CONCEPTO, NULL AS TotaL, CC_RECIBOS_VALORES.VL_IMPORTE
FROM         CC_RECIBOS INNER JOIN
                      CBTES ON CC_RECIBOS.ID_CBTE = CBTES.ID_CBTE INNER JOIN
                      CC_RECIBOS_VALORES ON CC_RECIBOS.ID_CC_RECIBO = CC_RECIBOS_VALORES.ID_CC_RECIBO INNER JOIN
                      CONCEPTOS ON CC_RECIBOS_VALORES.ID_CONCEPTO = CONCEPTOS.ID_CONCEPTO LEFT OUTER JOIN
                      RETENCIONES ON CC_RECIBOS_VALORES.ID_VALOR = RETENCIONES.ID_RETENCION LEFT OUTER JOIN
                      CAJA_VALORES ON CC_RECIBOS_VALORES.ID_VALOR = CAJA_VALORES.ID_VALOR INNER JOIN
                      ENTIDADES ON CC_RECIBOS.ID_ENTIDAD = ENTIDADES.ID_ENTIDAD INNER JOIN
                      ENTIDADES_UBICACIONES ON ENTIDADES.ID_ENTIDAD = ENTIDADES_UBICACIONES.ID_ENTIDAD AND 
                      ENTIDADES_UBICACIONES.ID_UBICACION_TIPO = 1 LEFT OUTER JOIN
                      LOCALIDADES ON ENTIDADES_UBICACIONES.ID_LOCALIDAD = LOCALIDADES.ID_LOCALIDAD LEFT OUTER JOIN
                      PROVINCIAS ON LOCALIDADES.ID_PROVINCIA = PROVINCIAS.ID_PROVINCIA LEFT OUTER JOIN
                      PAISES ON PROVINCIAS.ID_PAIS = PAISES.ID_PAIS INNER JOIN
                      VALOR_TIPOS ON CC_RECIBOS_VALORES.CD_VALOR_TIPO = VALOR_TIPOS.CD_VALOR_TIPO
WHERE     (CC_RECIBOS.NO_RECIBO = 00035656)
UNION ALL
SELECT     'Aplicacion' AS Tipo, ENTIDADES_1.DS_RAZON_SOCIAL, ENTIDADES_1.CD_CUIT, 
                      ENTIDADES_UBICACIONES_1.DS_DIRECCION + ' ' + ENTIDADES_UBICACIONES_1.DS_NUMERO + ' ' + ENTIDADES_UBICACIONES_1.DS_PISO + ' ' + ENTIDADES_UBICACIONES_1.DS_DPTO
                       AS Direccion, 
                      ' (' + ENTIDADES_UBICACIONES_1.CD_CP + ') ' + LOCALIDADES_1.DS_LOCALIDAD + ' - ' + PROVINCIAS_1.DS_PROVINCIA + ' - ' + PAISES_1.DS_PAIS AS Localidad, 
                      CC_RECIBOS_1.TP_RECIBO + '-' + CC_RECIBOS_1.NO_EMISOR + '-' + CC_RECIBOS_1.NO_RECIBO AS RECIBO, CC_RECIBOS_1.DT_EMISION, 
                      CBTES_1.DS_CBTE AS DS_VALOR_TIPO, CC_CBTES.DT_EMISION AS Expr1, CC_CBTES.DT_VENCE, CC_CBTES.ID_CBTE_EXTERNO, CBTES_1.DS_CBTE, 
                      CC_CBTES.VL_TOTAL AS Expr2, CC_RECIBOS_CBTES.VL_APLICA
FROM         CC_RECIBOS AS CC_RECIBOS_1 INNER JOIN
                      CBTES AS CBTES_2 ON CC_RECIBOS_1.ID_CBTE = CBTES_2.ID_CBTE INNER JOIN
                      CC_RECIBOS_CBTES ON CC_RECIBOS_1.ID_CC_RECIBO = CC_RECIBOS_CBTES.ID_CC_RECIBO INNER JOIN
                      CBTES AS CBTES_1 ON CC_RECIBOS_CBTES.ID_CBTE = CBTES_1.ID_CBTE INNER JOIN
                      CC_CBTES ON CC_RECIBOS_CBTES.ID_CC_APLICA = CC_CBTES.ID_CC_CBTE INNER JOIN
                      ENTIDADES AS ENTIDADES_1 ON CC_RECIBOS_1.ID_ENTIDAD = ENTIDADES_1.ID_ENTIDAD INNER JOIN
                      ENTIDADES_UBICACIONES AS ENTIDADES_UBICACIONES_1 ON ENTIDADES_1.ID_ENTIDAD = ENTIDADES_UBICACIONES_1.ID_ENTIDAD AND 
                      ENTIDADES_UBICACIONES_1.ID_UBICACION_TIPO = 1 LEFT OUTER JOIN
                      LOCALIDADES AS LOCALIDADES_1 ON ENTIDADES_UBICACIONES_1.ID_LOCALIDAD = LOCALIDADES_1.ID_LOCALIDAD LEFT OUTER JOIN
                      PROVINCIAS AS PROVINCIAS_1 ON LOCALIDADES_1.ID_PROVINCIA = PROVINCIAS_1.ID_PROVINCIA LEFT OUTER JOIN
                      PAISES AS PAISES_1 ON PROVINCIAS_1.ID_PAIS = PAISES_1.ID_PAIS
WHERE     (CC_RECIBOS_1.NO_RECIBO = 00035656)
ORDER BY Tipo";

$result = sqlsrv_query($conn_pagos, $query);


$rows = array();
while($r = sqlsrv_fetch_array( $result, SQLSRV_FETCH_ASSOC)) {    
    $rows[] = $r;
}
echo json_encode($rows);

exit();